### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [schober2/project6#1]
:+1: Looks fantastic! By far the most professional-looking `.erb` files I've seen on these projects so far. :tada: Would you mind if I showed these to some other students as an example?

One potential room for improvement in future projects though: it looks like `app.rb` has 8-space tabs instead of the standard 2-space for Ruby.

And just so you know for future reference, you don't actually need comments such as `# Gemfile` and `# app.rb` in your files. I just include them in code examples sometimes so you know which file the code would appear in.

**Comment by schober2** [comment]
Feel free to do so!

<div>-------- Original message --------</div><div>From: Chris Fritz notifications@github.com </div><div>Date:02/10/2015  17:58  (GMT-05:00) </div><div>To: schober2/project6 project6@noreply.github.com </div><div>Subject: [project6] Review notes (#1) </div><div>
</div>:+1: Looks fantastic! By far the most professional-looking `.erb` files I've seen on these projects so far. :tada: Would you mind if I showed these to some other students as an example?

One potential room for improvement in future projects though: it looks like `app.rb` has 8-space tabs instead of the standard 2-space for Ruby.

And just so you know for future reference, you don't actually need comments such as `# Gemfile` and `# app.rb` in your files. I just include them in code examples sometimes so you know which file the code would appear in.

---

Reply to this email directly or view it on GitHub:
https://github.com/schober2/project6/issues/1
